--liquibase formatted sql

--changeset nivethidhas:5
CREATE OR REPLACE TABLE STG_INCOME_BAND
(
IB_INCOME_BAND_SK NUMBER(38,0),
IB_LOWER_BOUND NUMBER(38,0),
IB_UPPER_BOUND NUMBER(38,0)
);

--rollback DROP TABLE STG_INCOME_BAND;

--changeset nivethidhas:6
INSERT INTO STG_INCOME_BAND (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.INCOME_BAND LIMIT 100);

--rollback DELETE FROM STG_INCOME_BAND;
