--liquibase formatted sql

--changeset nivethidhas:3
CREATE OR REPLACE TABLE STG_CUSTOMER_ADDRESS
(
CA_ADDRESS_SK NUMBER(38,0),
CA_ADDRESS_ID VARCHAR(16),
CA_STREET_NUMBER VARCHAR(10),
CA_STREET_NAME VARCHAR(60),
CA_STREET_TYPE VARCHAR(15),
CA_SUITE_NUMBER VARCHAR(10),
CA_CITY VARCHAR(60),
CA_COUNTY VARCHAR(30),
CA_STATE VARCHAR(2),
CA_ZIP VARCHAR(10),
CA_COUNTRY VARCHAR(20),
CA_GMT_OFFSET NUMBER(5,2),
CA_LOCATION_TYPE VARCHAR(20)
);

--rollback DROP TABLE STG_CUSTOMER_ADDRESS;

--changeset nivethidhas:4
INSERT INTO STG_CUSTOMER_ADDRESS (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER_ADDRESS LIMIT 100);

--rollback DELETE FROM STG_CUSTOMER_ADDRESS;
