--liquibase formatted sql
--changeset nivethidhas:JIRA-1234_EXTERNAL_DB-INVESTOR-VW_STG_ITEM_07-02-2025_15:04

USE DATABASE EXTERNAL_DB;
USE SCHEMA Investor;

CREATE OR REPLACE VIEW VW_STG_ITEM
AS
SELECT * FROM STG_ITEM;

--rollback DROP VIEW VW_STG_ITEM;

