--liquibase formatted sql
--changeset nivethidhas:JIRA-4567_ANALYTICS_DB-EDW-VW_DIM_ITEM_07-02-2025_15:10

USE DATABASE ANALYTICS_DB;
USE SCHEMA EDW;

CREATE OR REPLACE VIEW VW_DIM_ITEM
AS
SELECT * FROM DIM_ITEM;

--rollback DROP VIEW VW_DIM_ITEM;

