--liquibase formatted sql
--changeset nivethidhas:2

USE DATABASE ANALYTICS_DB;
USE SCHEMA EDW;

CREATE OR REPLACE VIEW VW_DIM_STORE_SALES
AS
SELECT * FROM DIM_STORE_SALES;

--rollback DROP VIEW VW_DIM_STORE_SALES;