--liquibase formatted sql
--changeset nivethidhas:1

USE DATABASE ANALYTICS_DB;
USE SCHEMA EDW;

CREATE OR REPLACE PROCEDURE DIM_ITEM
RETURNS TABLE (
I_ITEM_SK NUMBER(38,0),
I_ITEM_ID VARCHAR(16)
)
AS
SELECT I_ITEM_SK,I_ITEM_ID FROM VW_DIM_ITEM;

--rollback DROP PROCEDURE DIM_ITEM;

