--liquibase formatted sql
--changeset nivethidhas:2

USE DATABASE ANALYTICS_DB;
USE SCHEMA EDW;

CREATE OR REPLACE PROCEDURE DIM_STORE_SALES
RETURNS TABLE (
SS_ITEM_SK NUMBER(38,0),
SS_CUSTOMER_SK NUMBER(38,0)
)
AS
SELECT SS_ITEM_SK,SS_CUSTOMER_SK FROM VW_DIM_STORE_SALES;

--rollback DROP PROCEDURE DIM_STORE_SALES;