--liquibase formatted sql

--changeset nivethidhas:7
USE SCHEMA Offerings;
CREATE OR REPLACE TABLE STG_ORDER
(
O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR(79)
);

--rollback DROP TABLE STG_ORDER;

--changeset nivethidhas:8
INSERT INTO STG_ORDER (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS LIMIT 100);

--rollback DELETE FROM STG_ORDER;
