--liquibase formatted sql
--changeset nivethidhas:JIRA-1403_EXTERNAL_DB-INVESTOR-PART-14-02-2025_15:23
USE DATABASE EXTERNAL_DB;
USE SCHEMA Investor;

ALTER TABLE PART ADD COLUMN P_DATE DATE DEFAULT CURRENT_DATE();

--rollback DROP COLUMN P_DATE;

