--liquibase formatted sql
--changeset nivethidhas:JIRA-1403_EXTERNAL_DB-INVESTOR-REGION-14-02-2025_15:25
USE DATABASE EXTERNAL_DB;
USE SCHEMA Investor;

ALTER TABLE REGION MODIFY COLUMN R_NAME SET DATA TYPE STRING;

--rollback ALTER TABLE REGION MODIFY COLUMN R_NAME SET DATA TYPE VARCHAR(25);

