--liquibase formatted sql
--changeset nivethidhas:JIRA-1403_EXTERNAL_DB-INVESTOR-ORDERS-14-02-2025_15:33
USE DATABASE EXTERNAL_DB;
USE SCHEMA Investor;

ALTER TABLE ORDERS DROP COLUMN O_COMMENT;

--rollback ALTER TABLE ADD COLUMN O_COMMENT VARCHAR(79);

