--liquibase formatted sql
--changeset nivethidhas:JIRA-1403_EXTERNAL_DB-INVESTOR-SUPPLIER-14-02-2025_15:34
USE DATABASE EXTERNAL_DB;
USE SCHEMA Investor;

CREATE TABLE SUPPLIER (
S_SUPPKEY NUMBER(38,0),
S_NAME VARCHAR(25),
S_ADDRESS VARCHAR(40),
S_NATIONKEY NUMBER(38,0),
S_PHONE VARCHAR(15),
S_ACCTBAL NUMBER(12,2),
S_COMMENT VARCHAR(101)
);


--rollback DROP TABLE SUPPLIER;

--changeset nivethidhas:JIRA-1403_EXTERNAL_DB-INVESTOR-SUPPLIER-14-02-2025_15:35

INSERT INTO SUPPLIER (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.SUPPLIER LIMIT 50);

--rollback DELETE FROM SUPPLIER;