--liquibase formatted sql
--changeset nivethidhas:JIRA-1403_EXTERNAL_DB-INVESTOR-INVENTORY-14-02-2025_15:36
USE DATABASE EXTERNAL_DB;
USE SCHEMA Investor;

CREATE TABLE INVENTORY (
INV_DATE_SK NUMBER(38,0),
INV_ITEM_SK NUMBER(38,0),
INV_WAREHOUSE_SK NUMBER(38,0),
INV_QUANTITY_ON_HAND NUMBER(38,0)
);


--rollback DROP TABLE INVENTORY;

--changeset nivethidhas:JIRA-1403_EXTERNAL_DB-INVESTOR-INVENTORY-14-02-2025_15:37

INSERT INTO INVENTORY (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.INVENTORY LIMIT 50);

--rollback DELETE FROM INVENTORY;