--liquibase formatted sql
--changeset nivethidhas:JIRA-789_EXTERNAL_DB-INVESTOR-STG_INVENTORY-07-02-2025_18:47

USE DATABASE EXTERNAL_DB;
USE SCHEMA Investor;

CREATE OR REPLACE TABLE STG_INVENTORY
(
INV_DATE_SK NUMBER(38,0),
INV_ITEM_SK NUMBER(38,0),
INV_WAREHOUSE_SK NUMBER(38,0),
INV_QUANTITY_ON_HAND NUMBER(38,0)
);

--rollback DROP TABLE STG_INVENTORY;

--changeset nivethidhas:JIRA-789_EXTERNAL_DB-INVESTOR-STG_INVENTORY-07-02-2025_18:51

INSERT INTO STG_INVENTORY (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.INVENTORY LIMIT 100);

--rollback DELETE FROM STG_INVENTORY;

