--liquibase formatted sql
--changeset nivethidhas:JIRA-789_EXTERNAL_DB_INVESTOR_07-02-2025_16:54

USE DATABASE EXTERNAL_DB;
USE SCHEMA Investor;

CREATE OR REPLACE VIEW VW_STG_ITEM
AS
SELECT * FROM STG_ITEM LIMIT 10;

--rollback DROP VIEW VW_STG_ITEM;