--liquibase formatted sql
--changeset nivethidhas:JIRA-789_EXTERNAL_DB-INVESTOR-VW_STG_ITEM-07-02-2025_16:54

USE DATABASE EXTERNAL_DB;
USE SCHEMA Investor;

CREATE OR REPLACE VIEW VW_STG_ITEM
AS
SELECT * FROM STG_ITEM LIMIT 10;

--rollback DROP VIEW VW_STG_ITEM;
