--liquibase formatted sql
--changeset nivethidhas:JIRA-999_EXTERNAL_DB_INVESTOR_07-02-2025_17:19

USE DATABASE EXTERNAL_DB;
USE SCHEMA Investor;

CREATE OR REPLACE VIEW VW_STG_ITEM
AS
SELECT * FROM STG_ITEM LIMIT 50;

--rollback CREATE OR REPLACE VIEW VW_STG_ITEM AS SELECT * FROM STG_ITEM LIMIT 10;
