--liquibase formatted sql
--changeset nivethidhas:JIRA-1402_EXTERNAL_DB-INVESTOR-ORDERS-14-02-2025_15:09
USE DATABASE EXTERNAL_DB;
USE SCHEMA Investor;

CREATE TABLE ORDERS (
O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR(79)
);


--rollback DROP TABLE ORDERS;

--changeset nivethidhas:JIRA-1402_EXTERNAL_DB-INVESTOR-ORDERS-14-02-2025_15:10

INSERT INTO ORDERS (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS LIMIT 10);

--rollback DELETE FROM ORDERS;