--liquibase formatted sql
--changeset nivethidhas:JIRA-1402_EXTERNAL_DB-INVESTOR-SHIP_MODE-14-02-2025_15:15
USE DATABASE EXTERNAL_DB;
USE SCHEMA Investor;

CREATE TABLE SHIP_MODE (
SM_SHIP_MODE_SK NUMBER(38,0),
SM_SHIP_MODE_ID VARCHAR(16),
SM_TYPE VARCHAR(30),
SM_CODE VARCHAR(10),
SM_CARRIER VARCHAR(20),
SM_CONTRACT VARCHAR(20)
);


--rollback DROP TABLE SHIP_MODE;

--changeset nivethidhas:JIRA-1402_EXTERNAL_DB-INVESTOR-SHIP_MODE-14-02-2025_15:16

INSERT INTO SHIP_MODE (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.SHIP_MODE LIMIT 20);

--rollback DELETE FROM SHIP_MODE;