--liquibase formatted sql
--changeset nivethidhas:JIRA-1402_EXTERNAL_DB-INVESTOR-PART-14-02-2025_15:19
USE DATABASE EXTERNAL_DB;
USE SCHEMA Investor;

CREATE TABLE PART (
P_PARTKEY NUMBER(38,0),
P_NAME VARCHAR(55),
P_MFGR VARCHAR(25),
P_BRAND VARCHAR(10),
P_TYPE VARCHAR(25),
P_SIZE NUMBER(38,0),
P_CONTAINER VARCHAR(10),
P_RETAILPRICE NUMBER(12,2),
P_COMMENT VARCHAR(23)
);


--rollback DROP TABLE PART;

--changeset nivethidhas:JIRA-1402_EXTERNAL_DB-INVESTOR-PART-14-02-2025_15:20

INSERT INTO PART (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART LIMIT 50);

--rollback DELETE FROM PART;
