--liquibase formatted sql

--changeset nivethidhas:16
USE DATABASE ANALYTICS_DB;
USE SCHEMA EDW;
CREATE OR REPLACE TABLE DIM_INCOME_BAND
(
IB_INCOME_BAND_SK NUMBER(38,0),
IB_LOWER_BOUND NUMBER(38,0),
IB_UPPER_BOUND NUMBER(38,0),
IB_EFFECTIVE_DATE TIMESTAMP,
IB_END_DATE TIMESTAMP
);

--rollback DROP TABLE DIM_INCOME_BAND;

--changeset nivethidhas:17
USE SCHEMA EDW;
INSERT INTO DIM_INCOME_BAND (IB_INCOME_BAND_SK,IB_LOWER_BOUND,IB_UPPER_BOUND,IB_EFFECTIVE_DATE,IB_END_DATE)
VALUES (1, 0,10000,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());


--rollback DELETE FROM TABLE DIM_INCOME_BAND;
