--liquibase formatted sql

--changeset nivethidhas:13
USE DATABASE ANALYTICS_DB;
USE SCHEMA EDW;
CREATE OR REPLACE TABLE DIM_CUSTOMER
(
C_CUSTOMER_SK NUMBER(38,0),
C_CUSTOMER_ID VARCHAR(16),
C_CURRENT_CDEMO_SK NUMBER(38,0),
C_CURRENT_HDEMO_SK NUMBER(38,0),
C_CURRENT_ADDR_SK NUMBER(38,0),
C_FIRST_SHIPTO_DATE_SK NUMBER(38,0),
C_FIRST_SALES_DATE_SK NUMBER(38,0),
C_SALUTATION VARCHAR(10),
C_FIRST_NAME VARCHAR(20),
C_LAST_NAME VARCHAR(30),
C_PREFERRED_CUST_FLAG VARCHAR(1),
C_BIRTH_DAY NUMBER(38,0),
C_BIRTH_MONTH NUMBER(38,0),
C_BIRTH_YEAR NUMBER(38,0),
C_BIRTH_COUNTRY VARCHAR(20),
C_LOGIN VARCHAR(13),
C_EMAIL_ADDRESS VARCHAR(50),
C_LAST_REVIEW_DATE VARCHAR(10),
C_EFFECTIVE_DATE TIMESTAMP,,
C_END_DATE TIMESTAMP
);

--rollback DROP TABLE DIM_CUSTOMER;

--changeset nivethidhas:14
INSERT INTO DIM_CUSTOMER (C_CUSTOMER_SK, C_CUSTOMER_ID, C_CURRENT_CDEMO_SK, C_CURRENT_HDEMO_SK, 
C_CURRENT_ADDR_SK, C_FIRST_SHIPTO_DATE_SK, C_FIRST_SALES_DATE_SK, C_SALUTATION, C_FIRST_NAME, C_LAST_NAME, 
C_PREFERRED_CUST_FLAG, C_BIRTH_DAY, C_BIRTH_MONTH, C_BIRTH_YEAR, C_BIRTH_COUNTRY, C_LOGIN, C_EMAIL_ADDRESS, 
C_LAST_REVIEW_DATE,C_EFFECTIVE_DATE,C_END_DATE) VALUES (70253635, 'AAAAAAAADEMPPCEA', 789736, 6719, 31493302, 2449691, 2449661, 'Mrs.', 'Albert', 'Williamson', 'Y', 17, 4, 1927, 'PITCAIRN', NULL, 'Albert.Williamson@2vnJHAhKc0yG1McxZ.com', '2452356',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());


--rollback DELETE FROM TABLE DIM_CUSTOMER;
