--liquibase formatted sql

--changeset nivethidhas:18
USE DATABASE ANALYTICS_DB;
USE SCHEMA EDW;
CREATE OR REPLACE TABLE DIM_ORDER
(
O_ORDERKEY NUMBER(38,0),
O_CUSTKEY NUMBER(38,0),
O_ORDERSTATUS VARCHAR(1),
O_TOTALPRICE NUMBER(12,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY VARCHAR(15),
O_CLERK VARCHAR(15),
O_SHIPPRIORITY NUMBER(38,0),
O_COMMENT VARCHAR(79),
O_EFFECTIVE_DATE TIMESTAMP,
O_END_DATE TIMESTAMP
);

--rollback DROP TABLE DIM_ORDER;

--changeset nivethidhas:19
USE SCHEMA EDW;
INSERT INTO DIM_ORDER(O_ORDERKEY,O_CUSTKEY,O_ORDERSTATUS,O_TOTALPRICE,O_ORDERDATE,O_ORDERPRIORITY,O_CLERK,O_SHIPPRIORITY,O_COMMENT,O_EFFECTIVE_DATE,O_END_DATE)VALUES(
5778658501,68750986,F,3245.47,1992-08-02,"3-MEDIUM","Clerk#000977658",0,"ve the slyly final requests. furiously special acc",CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());


--rollback DELETE FROM TABLE DIM_ORDER;
