--liquibase formatted sql
--changeset nivethidhas:JIRA-4567_ANALYTICS_DB-EDW-DIM_ITEM_07-02-2025_15:06

USE DATABASE ANALYTICS_DB;
USE SCHEMA EDW;

CREATE OR REPLACE TABLE DIM_ITEM
(
I_ITEM_SK NUMBER(38,0),
I_ITEM_ID VARCHAR(16),
I_REC_START_DATE DATE,
I_REC_END_DATE DATE,
I_ITEM_DESC VARCHAR(200),
I_CURRENT_PRICE NUMBER(7,2),
I_WHOLESALE_COST NUMBER(7,2),
I_BRAND_ID NUMBER(38,0),
I_BRAND VARCHAR(50),
I_CLASS_ID NUMBER(38,0),
I_CLASS VARCHAR(50),
I_CATEGORY_ID NUMBER(38,0),
I_CATEGORY VARCHAR(50),
I_MANUFACT_ID NUMBER(38,0),
I_MANUFACT VARCHAR(50),
I_SIZE VARCHAR(20),
I_FORMULATION VARCHAR(20),
I_COLOR VARCHAR(20),
I_UNITS VARCHAR(10),
I_CONTAINER VARCHAR(10),
I_MANAGER_ID NUMBER(38,0),
I_PRODUCT_NAME VARCHAR(50)
);

--rollback DROP TABLE DIM_ITEM;

--changeset nivethidhas:JIRA-4567_ANALYTICS_DB-EDW-DIM_ITEM_07-02-2025_15:07
INSERT INTO DIM_ITEM (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.ITEM LIMIT 100);

--rollback DELETE FROM DIM_ITEM;



